'BrauneDigital\MessageBundle\Entity\BaseMessage':
    type: mappedSuperclass
    table: bd_msg_message
    fields:
        text:
            type: text
            nullable: false
        date:
            type: datetime
            nullable: false
        subject:
            type: string
            length: 255
            nullable: true