'BrauneDigital\MessageBundle\Entity\BaseMessage':
    type: mappedSuperclass
    table: bd_msg__message
    fields:
        content:
            type: text
            nullable: false
        createdAt:
            type: datetime
            nullable: false
        subject:
            type: string
            length: 255
            nullable: true
