'BrauneDigital\MessageBundle\Entity\BaseRecipient':
    type: mappedSuperclass
    table: bd_msg__user_message
    fields:
        readAt:
            type: datetime
            options:
                default: null
            nullable: true
