'BrauneDigital\MessageBundle\Entity\BaseUserHasMessage':
    type: mappedSuperclass
    table: bd_msg__user_message
    fields:
        wasRead:
            type: datetime
            options:
                default: null
            nullable: true