services:
    braune_digital_message.conversation_manager:
        class: 'BrauneDigital\MessageBundle\Service\ConversationManager'
        arguments: ['%braune_digital_message.entities%', "@doctrine.orm.entity_manager"]
