BrauneDigital\MessageBundle\Entity\BaseMessage:
    properties:
        content:
            - NotBlank:
                message: 'braune_digital_message.message.content.not_blank'
        createdAt:
            - NotNull: ~
