BrauneDigital\MessageBundle\Entity\BaseConversation:
    exclusion_policy: ALL
    access_type: public_method
    properties:
        subjects:
            expose: true
            type: string
        created:
            expose: true
            type: DateTime
        members:
            expose: true
        messages:
            expose: true