BrauneDigital\MessageBundle\Entity\BaseMessage:
    exclusion_policy: ALL
    access_type: public_method
    properties:
        content:
            expose: true
            type: string
        subject:
            expose: true
            type: string
        createdAt:
            expose: true
            type: DateTime
