BrauneDigital\MessageBundle\Entity\BaseUserHasMessage:
    exclusion_policy: ALL
    access_type: public_method
    properties:
        wasRead:
            expose: true
            type: DateTime
        message:
            expose: true