BrauneDigital\MessageBundle\Entity\BaseUserHasConversation:
    exclusion_policy: ALL
    access_type: public_method
    properties:
        joinedOn:
            expose: true
            type: DateTime
        leftOn:
            expose: true
            type: DateTime
        active:
            expose: true
            type: boolean
        isAdmin:
            expose: true
            type: boolean
        messages:
            expose: true
        conversation:
            expose: true